# キーワード設定
# タイトルや要約に含まれていれば通知するキーワード（重み付き）
# 各キーワードには重み（weight）を設定できます
# 重みが高いほど、そのキーワードにマッチした際のスコアが高くなります

keywords:
  - keyword: "vector graphics generation|vector graphic synthesis|vector-based image generation|generative vector graphics|procedural vector graphics"
    weight: 3
  - keyword: "code generation|vector graphics code generation|SVG code generation|TikZ code generation|LaTeX vector graphics generation"
    weight: 3
  - keyword: "RAG|retrieval-augmented generation|retrieval augmented generation"
    weight: 1
  - keyword: "LLM|large language model|large language models|LLM for vector graphics|large language model vector graphics generation"
    weight: 1
  - keyword: "TikZ generation|LaTeX TikZ code generation|TikZ"
    weight: 3
  - keyword: "LaTeX|latex|LaTeX vector graphics"
    weight: 2
  - keyword: "SVG generation|Scalable Vector Graphics generation|SVG synthesis|scalable vector graphics generation"
    weight: 2
  - keyword: "xml generation|xml"
    weight: 2
  - keyword: "agent|agentic|agentic model|agentic models|agentic model vector graphics generation"
    weight: 2
  - keyword: "scientific diagram generation|technical illustration generation|chart and plot code generation|vectorized artwork generation"
    weight: 2

# 重みの設定例
# - weight: 1  # 基本スコア（タイトル×2 + 要約×1）
# - weight: 2  # 2倍のスコア（タイトル×4 + 要約×2）
# - weight: 3  # 3倍のスコア（タイトル×6 + 要約×3）
# - weight: 4  # 4倍のスコア（タイトル×8 + 要約×4）

# 正規表現の使用例
# 複数のキーワードをOR条件で指定したい場合:
# - keyword: "vision-language|VLM|caption"  # vision-language または VLM または caption
# - keyword: "detection|segmentation"       # detection または segmentation

# 大文字小文字は区別されません（自動的にIGNORECASEが適用されます）
