# キーワード設定
# タイトルや要約に含まれていれば通知するキーワード（正規表現でOR条件）

keywords:
  - "vector graphics|vector|graphics"
  - "code|code generation"
  - "RAG|retrieval-augmented generation|retrieval-augmented generation|retrieval augmented generation"
  - "LLM|large language model|large language models"
  - "TikZ"
  - "LaTeX|latex"
  - "SVG|Scalable Vector Graphics|scalable vector graphics"
  - "agent|agentic|agentic model|agentic models"

  
# 正規表現の使用例
# 複数のキーワードをOR条件で指定したい場合:
# - "vision-language|VLM|caption"  # vision-language または VLM または caption
# - "detection|segmentation"       # detection または segmentation

# 大文字小文字は区別されません（自動的にIGNORECASEが適用されます）
