# キーワード設定
# タイトルや要約に含まれていれば通知するキーワード（正規表現でOR条件）

keywords:
  # 機械学習・AI関連
  - "vector"
  - "diffusion"
  - "LoRA"
  
  # 図表・可視化関連
  - "TikZ"
  
  # 追加したいキーワードは以下に記述
  # - "transformer"
  # - "attention"
  # - "neural network"
  # - "deep learning"
  # - "computer vision"
  # - "natural language processing"

# 正規表現の使用例
# 複数のキーワードをOR条件で指定したい場合:
# - "vision-language|VLM|caption"  # vision-language または VLM または caption
# - "detection|segmentation"       # detection または segmentation

# 大文字小文字は区別されません（自動的にIGNORECASEが適用されます）
